Learn step-by-step with me, how to use pandas to create, read, and write data

# **CREATING DATA**

In [1]:
# To get started, you need to import the library "pandas"

import pandas as pd

Note that there are two main objects in pandas: **the DataFrame and the Series**

- **the DataFrame:** In python, a table is being referred to as a DataFrame.
It usually contains an array of individual entries, 
each of which has a certain value. 
Each entry corresponds to a row and a column.

In [4]:
#   Let us consider a simple DataFrame:

pd.DataFrame({"Male":[70, 41], "Female":[151, 22]})

   Male  Female
0    70     151
1    41      22